# Generated by Django 6.0.7 on 2026-09-16 07:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_lead_lead_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='contact_owner',
        ),
        migrations.AddField(
            model_name='lead',
            name='contact_owners',
            field=models.ManyToManyField(blank=True, related_name='assigned_leads', to=settings.AUTH_USER_MODEL),
        ),
    ]
