# Generated by Django 6.0.7 on 2026-09-16 09:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_merge_20260825_1941'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_owner',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_owners',
            field=models.ManyToManyField(blank=True, related_name='owned_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
