# Generated by Django 6.0.7 on 2026-09-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0003_call_duration_alter_call_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='twilio_call_sid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='call',
            name='twilio_status',
            field=models.CharField(blank=True, choices=[('queued', 'Queued'), ('initiated', 'Initiated'), ('ringing', 'Ringing'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('busy', 'Busy'), ('no-answer', 'No Answer'), ('canceled', 'Canceled'), ('failed', 'Failed')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='call_outcome',
            field=models.CharField(choices=[('connected', 'Connected'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('left_voicemail', 'Left Voicemail'), ('wrong_number', 'Wrong Number'), ('callback_requested', 'Callback Requested'), ('not_interested', 'Not Interested'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
