# Generated by Django 6.0.7 on 2026-09-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0004_call_twilio_call_sid_call_twilio_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='customer_twilio_call_sid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='call',
            name='user_twilio_call_sid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
