# Generated by Django 6.0.7 on 2026-09-10 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0005_call_customer_twilio_call_sid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='customer_twilio_call_sid',
        ),
        migrations.RemoveField(
            model_name='call',
            name='user_twilio_call_sid',
        ),
    ]
