# Generated by Django 6.0.7 on 2026-09-10 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0006_remove_call_customer_twilio_call_sid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='customer_twilio_call_sid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='user_twilio_call_sid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
