# Generated by Django 6.0.7 on 2026-09-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0007_call_customer_twilio_call_sid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='call_mode',
            field=models.CharField(choices=[('direct', 'Direct'), ('bridge', 'Bridge')], default='direct', max_length=20),
        ),
    ]
